# ZMK Studio Support
CONFIG_ZMK_STUDIO=y

# Disable Studio lock for seamless user experience
CONFIG_ZMK_STUDIO_LOCKING=n

# Power management
CONFIG_ZMK_SLEEP=y

# Fix for nice!nano v2 power consumption
CONFIG_BOARD_ENABLE_DCDC_HV=n

# Enable macros
CONFIG_ZMK_KEYMAP_HAS_MACROS=y