# Enable ZMK Studio
CONFIG_ZMK_STUDIO=y

# Disable the lock for simple user experience
CONFIG_ZMK_STUDIO_LOCKING=n

# Enable USB and Bluetooth RPC transports
CONFIG_ZMK_RPC_OVER_USB=y
CONFIG_ZMK_RPC_OVER_BLE=y